- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: 
      location: 
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: 
      name: 
      address_prefixes: ""
  - name: Add subnet
    azure_rm_subnet:
      resource_group: 
      name: 
      address_prefix: ""
      virtual_network: 
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: 
      allocation_method: Static
      name: 
    register: 
  - name: Dump public IP for VM which will be created
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: 
      name: 
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: 
      name: 
      virtual_network: 
      subnet: 
      public_ip_name: 
      security_group: 
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: 
      name: 
      vm_size: 
      admin_username: azureuser
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: <your-key-data>
      network_interfaces: 
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest